pipeline {
	
	agent {
		label 'docker'
	}

	options {
		disableConcurrentBuilds()
		timeout(time: 30, unit: 'MINUTES')

	}

	environment {

		HOME = '.'
		POM_VERSION = readMavenPom().getVersion()
		POM_ARTIFACT = readMavenPom().getArtifactId()
		git_hash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()

	}
	stages {
		stage("Build") {
			steps {
				script {
					mvn clean install

				}
			}
		}
	}
}
