pipeline {
	
	agent {
		label 'docker'
	}

	options {
		disableConcurrentBuilds()
		timeout(time: 30, unit: 'MINUTES')

	}

	environment {

		HOME = 'workspace/maven-pipeline/maven/my-app'
		//POM_VERSION = readMavenPom().getVersion()
		//POM_ARTIFACT = readMavenPom().getArtifactId()
		git_hash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()

	}
	stages {
		stage("Build") {
			steps {
				script {
				    ws(HOME){
				    POM_VERSION = readMavenPom().getVersion()
		            POM_ARTIFACT = readMavenPom().getArtifactId()
				    }
				    sh '''cd maven/my-app && pwd
					/usr/local/bin/mvn clean install
					'''

				}
			}
		}
	}
	post {
	    always{
	        echo "Completed"
	        
	    }
	    cleanup {
	        cleanWs(
	            deleteDirs: true
	            )
	    }
	}
}
